### ISSUE TITLE
Add compiled release

### ISSUE THREAD

**Issue by Keith94** [BandW2011/Emergency-Alarm-Clock#1]
Can you release a compiled version (binary) in the future for testing? Is it ready to use yet?

**Comment by BandW2011** [comment]
I've added a binary, but I've only been able to test it on my computer and OS (Ubuntu 16.04 LTS 64-bit). So far the project only works using the current directory structure (i.e. binary is in bin/ and resources are in res/) because I don't understand very well how to get resources for SFML in other directories, or in any kind of package.

**Comment by Keith94** [comment]
Okay, I was hoping to test it on Windows, but is it Linux only for now?

**Comment by Keith94** [comment]
I found an alternative, so no worries.
